export const MENU_ACTIONS = {
  GET_MENU: 'GET_MENU',
  GET_MENU_SUCCESS: 'GET_MENU_SUCCESS',
  GET_MENU_FAILURE: 'GET_MENU_FAILURE'
}

export const DETAIL_ACTIONS = {
  GET_DETAIL: 'GET_DETAIL',
  GET_DETAIL_SUCCESS: 'GET_DETAIL_SUCCESS',
  GET_DETAIL_FAILURE: 'GET_DETAIL_FAILURE'
}

export const ORDER_ACTIONS = {
  ADD_ORDER_DETAIL_SUCCESS: 'ADD_ORDER_DETAIL_SUCCESS',
  CONFIRM_ORDER: 'CONFIRM_ORDER'
}

export const AUTH_ACTIONS = {
  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT: 'LOGOUT',
  GET_USER_SUCCESS: 'GET_USER_SUCCESS'
}
